version: 0.2

phases:

  install:
    runtime-versions:
      java: corretto8

  build:
    commands:
      - mvn install

      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - mv target/lavagna.war lavagna.war     
         
      - docker build -f Dockerfile_lavagna -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG             
  
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

      - mv lavagna.war ROOT.war

#      - zip -r lavagna.zip docker-compose.yml .ebextensions

#      - mkdir prod
#      - mv docker-compose.yml .ebextensions prod
      - ls -la
      - cp -r $CODEBUILD_SRC_DIR_Source2/. ./
      - ls -la

artifacts:
  
  files:
#    - lavagna.zip
#    - prod/**/*
    - docker-compose.yml
    - .env
    - .ebextensions/**/*

  secondary-artifacts:
    
    simple_war:
      files: 
        - ROOT.war
    
    embedded_jetty:
      base-directory: target
      files:
        - lavagna-jetty-console.war

cache:
  paths:
    - '/root/.m2/**/*'