version: 0.2

phases:

  install:
    runtime-versions:
      java: corretto8

  build:
    commands:
      - mvn install

      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - mv target/lavagna.war lavagna.war     
         
      - docker build -f Dockerfile_lavagna -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG             
  
  post_build:
    commands:.
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

      - mv lavagna.war ROOT.war  

artifacts:
  
  files:
    - ROOT.war

  secondary-artifacts:
    embedded_jetty:
      base-directory: target
      files:
        - lavagna-jetty-console.war

cache:
  paths:
    - '/root/.m2/**/*'