version: '3.8'

services:
  service_lavagna_server:
    container_name: lavagna_server
    image: 679954501512.dkr.ecr.us-east-1.amazonaws.com/lavagna:latest
    ports:
      - 80:8080
    environment:
      JAVA_OPTIONS: >
        -Ddatasource.dialect=${RDS_DIALECT}
        -Ddatasource.url=${DB_DRIVER}${RDS_ENDPOINT}:${RDS_PORT}/${DB_NAME}
        -Ddatasource.username=${DB_LOGIN} 
        -Ddatasource.password=${DB_PASS}
        -Dspring.profiles.active=${APP_MODE}
